### ISSUE TITLE
Signals acquired on the STEMLAB-10 do not fall on multiples of 2mV as expected

### ISSUE THREAD

**Issue by sefffal** [RedPitaya/RedPitaya#117]
Hello,
I've been using the Oscilloscope & Signal Generator web application and the SCPI interface and I'd like to understand some of the readings I'm seeing.
The bottom four bits of data from the ADC are zeroed out in the hardware, so the signals acquired should only have values that are some multiple of 40V/2^10=39mV. Instead, I'm seeing a clusters of values that are close to but not exactly multiples of 40mV -- see attached screenshots.

Is there some interpolation or time averaging taking place at the FPGA level?

The waveforms in the screenshots were was captured using SCPI and using the built in Oscilloscope app.

SCPI:
![image](https://user-images.githubusercontent.com/7330605/27091784-2ea76688-502f-11e7-89cb-5206eb01cdfb.png)

Oscilloscope Web App:
![image](https://user-images.githubusercontent.com/7330605/27091852-62310ef0-502f-11e7-993f-66a2f0c67fb5.png)
 
I am particularly interested in why the clusters in the second screen shot are sloped upwards and then downwards.

Thank you,
-Will

**Comment by jeras** [comment]
There is a 14 bit digital filter between the ADC and the acquisition buffer. The input into this filter is MSB aligned, so for 10bit ADC, dat[3:0]=4'b0. This filter can and does produce nonzero LSB values.
The behavior you are seeing is not time interpolation.
