### ISSUE TITLE
path to toolchain external path is hardcoded into OS/buildroot/config

### ISSUE THREAD

**Issue by mgmarino** [RedPitaya/RedPitaya#12]
Ideally this could be patched using environmental variables during build/configure time.  At the very least, it should be noted in the INSTALL file (similarly to /var/git/*.git directories) that this must be changed if the toolchain is elsewhere.

**Comment by jeras** [comment]
In version 0.94 the Xilinx provided toolchain is only used to compile FSBL. U-Boot, Linux Kernel and all user space are compiled using the Linaro compiler. We tried to remove all hardcoded compiler paths, but moving to a different compiler might still require some modifications to Buildroot configuration.
