### ISSUE TITLE
To get two signals from function generator

### ISSUE THREAD

**Issue by vaishsuri** [RedPitaya/RedPitaya#127]
Hi!
I am new to Red Pitaya (or any device of this kind). My task is to get two signals from an external signal generator to the red pitaya via the two ADC input ports and compute their phase difference and frequency difference. I should be able to do it in python by connecting to the server and not through web interface. If someone could guide me on how to give it a start, it would be really helpful. I have been trying out to generate signal pulses and getting a signal based on a trigger pulse, etc., but none of these have given me a proper idea on what's happening inside.

Thanks in Advance.

**Comment by amike80** [comment]
take a look at [this](https://github.com/RedPitaya/jupyter/blob/9f3cfd3e20c2b4ddae8bdc1762ed6154f917f3ff/examples/gen_sync_two_channel.ipynb) jupyter example. For more details look in the [documentation](http://redpitaya.readthedocs.io/en/latest/appsFeatures/jupyter/Jupyter.html).
