### ISSUE TITLE
fpga/ip folder missing ??

### ISSUE THREAD

**Issue by JohannesWoeber** [RedPitaya/RedPitaya#128]
Hi,
I am new to vivado and tried using your red_pitaya_vivado_project.tcl script.
I looked at older versions of the repo and it disappeared around release 0.95

Error Message:
couldn't read file "ip/system.tcl": no such file or directory

**Comment by jeras** [comment]
After running settings in the project root folder:
```
$ . settings.sh
```
Change to the FPGA directory and do:
```
$ make PRJ=classic
```
The FPGA project name (`PRJ`) can also be one of `v0.94`, `mercury` or `logic`.

**Comment by JohannesWoeber** [comment]
Thank you very much for your help. Much appreciated.
