### ISSUE TITLE
Logic Analyzer: When restarting all DIN are selected in the menu

### ISSUE THREAD

**Issue by cmorty** [RedPitaya/RedPitaya#129]
Reproduce:
 *  Start Logic Analyzer
 * Deselect some DINs
 * Exit and reenter Ligic Analyzer

Expected:
 * Deselected probes are not shown
 * The deselected probes are not checked in the digital-menu

Actual:
 * Deselected probes are not shown (OK)
 * All DINs are checked in the digital-menu

Version 0.96

**Comment by b-swat** [comment]
Thanks for pointing out the bug, it will be fixed in the next release
