### ISSUE TITLE
Python scripts can not initialize as any non-root user

### ISSUE THREAD

**Issue by hubgitti** [RedPitaya/RedPitaya#133]
Using your jupyter example "osc_trigger_forced" on the console, a initialization fails with the following error:
mkdir: cannot create directory ‘/sys/kernel/config/device-tree/overlays/mercury’: Permission denied

After running the script as root or via your jupyter nginx web interface everything is working fine also as non root user.

**Comment by jeras** [comment]
By default only root has permissions to create overlays, and I have not seen any mentions of non root user access while reading related documentation. You might try changing directory access rights, but you would have to do it every time at boot, since the path is created dynamically.
