### ISSUE TITLE
Contratiction in calibration: NGINX web oscilloscope, cli tool calib

### ISSUE THREAD

**Issue by hubgitti** [RedPitaya/RedPitaya#134]
After a calibration of the fast input channels using your nginx web oscilloscope, acquiring the calibration data using your tool "calib" seems to fail. The offset values for the HV voltage gain settings are not displayed.

**Comment by hubgitti** [comment]
To the members still working for RedPitaya: To my humble opinion, this issue needs a fix or solid workaround. Calibration would be quite important to me as I'm using the 14bit version of your StemLab.

**Comment by b-swat** [comment]
The calibration scheme has been completely redesigned, it is no longer in the oscilloscope.
