### ISSUE TITLE
Missing attribution of authortship of images in doc/developerGuide/125-14/cooling.rst

### ISSUE THREAD

**Issue by piranha32** [RedPitaya/RedPitaya#142]
The images and plot used on cooling page are copied from https://rroeng.blogspot.com/2014/03/keep-your-red-pitaya-cool.html
As the author of the post, and all the files you copied, I give you permission to use them in the documentation, but please add attribution, and a link to the source page.

**Comment by amike80** [comment]
Hi,

I've added links to your blog to all images. You'll be able to see them when the new document builds on ReadTheDoc, until then it is visible on our github. 

kind regards
