### ISSUE TITLE
hardware problem with 0.98 release?

### ISSUE THREAD

**Issue by xiaoweihua** [RedPitaya/RedPitaya#143]
I copyed the classic folder to fpga folder, and make project to build the hardware , find that the osc is not connect to the ps system, any more, the xdc file is wrong. can you repair this problem?

**Comment by amike80** [comment]
There is no problem with xdc file. What you did is wrong. Don't copy files left and right. There is a reason for their placement.

If you want to build classic project use command _make -f Makefile classic_
