### ISSUE TITLE
where to get help file?

### ISSUE THREAD

**Issue by xiaoweihua** [RedPitaya/RedPitaya#144]
this project is very complex including hardware and software, how to quickly get started with it? where to find the register allocate and usage?

**Comment by amike80** [comment]
I recommend starting with the [documentation](http://redpitaya.readthedocs.io/en/latest/)

**Comment by waqarrashid33** [comment]
Documentaion is not the best one.. Hopefully I will make PR once I understand the system. It will make it a bit friendly to new comers.
