### ISSUE TITLE
violation of the VNA application license

### ISSUE THREAD

**Issue by pavel-demin** [RedPitaya/RedPitaya#147]
Dear RedPitaya developers,

The way you've copied my [VNA application](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/vna) to your repository seems to violate the terms of the MIT license that normally comes together with my VNA application.

Please fix it by copying the [LICENSE](https://github.com/pavel-demin/red-pitaya-notes/blob/master/LICENSE) file from my repository to [apps-free/stemlab_vna](https://github.com/RedPitaya/RedPitaya/tree/master/apps-free/stemlab_vna).

Best regards,

Pavel

**Comment by amike80** [comment]
Yes you were correct, 
the missing files are now copied over.

We apologize for any inconvenience this may have caused.

kind regards

RPteam
