### ISSUE TITLE
pyrpl/modules.py - Caught in recursive loop when trying to dig for pyrpl instance causing hanging on all r.scope.* calls

### ISSUE THREAD

**Issue by mkphuthi** [RedPitaya/RedPitaya#150]
Forgive me if my format is terrible, I do not usually file issues.

Whenever I call/assign any member of redpitaya.scope, my code hangs forever and I have traced it back to the pyrpl/modules.py in the pyrpl function. I do not have a good enough understanding of the code to make a suggestion but could this be a bug?

    def pyrpl(self):
        """
        Recursively looks through patent modules untill pyrpl instance is
        reached.
        """
        from .pyrpl import Pyrpl
        parent = self.parent
        while (not isinstance(parent, Pyrpl)):
            parent = parent.parent
        return parent

**Comment by lneuhaus** [comment]
Hi, 
I have copy-pasted your issue in the pyrpl repo where it belongs. Please see my  answer there.
