### ISSUE TITLE
compiling scpi-server: wrong interface for SCPI_Init(...)

### ISSUE THREAD

**Issue by KarlZeilhofer** [RedPitaya/RedPitaya#152]
Hi, 

I'm trying to compile the scpi-server as a standallone application for the raspberry pi. 
I've cloned the RedPitaya repo https://github.com/RedPitaya/RedPitaya.git and then cloned into the directory RedPitaya/scpi-server the scpi-parser from https://github.com/RedPitaya/scpi-parser.git

Then the folder structure is as documented in the README.md
![2018-07-22_003](https://user-images.githubusercontent.com/2773445/43048654-80d5e682-8deb-11e8-87fe-973c41dbe379.png)

After fixing an initialization error for the `scpi_context.registers` (line 230 in scpi-commands.c) by changing the declaration of `struct _scpi_t`
from 
```
 {
	...
	scpi_reg_val_t registers[SCPI_REG_COUNT];
	...
};
```
to
```
 {
	...
	scpi_reg_val_t* registers;
	...
};
```
I'm stuck at another rather big problem:
`scpi-server.c` calls in line 234 `SCPI_Init(&scpi_context);`, but the prototype requires many more arguments: 
```
    void SCPI_Init(scpi_t * context,
            const scpi_command_t * commands,
            scpi_interface_t * interface,
            const scpi_unit_def_t * units,
            const char * idn1, const char * idn2, const char * idn3, const char * idn4,
            char * input_buffer, size_t input_buffer_length,
            scpi_error_t * error_queue_data, int16_t error_queue_size);
```

I think there is something mixed up with different repo versions of scpi-server and scpi-parser. 

Can anyone help me, how to get this piece of code compiled?

Thanks, Karl

**Comment by KarlZeilhofer** [comment]
Found the change in May 2015 (!!)
![2018-07-22_004](https://user-images.githubusercontent.com/2773445/43048838-8a28ca12-8dee-11e8-9695-c706b0e03ada.png)

Why is this inconsistency still there in RedPitaya?

**Comment by b-swat** [comment]
Code updated for latest versions.
Incompatibility fixed.
