### ISSUE TITLE
Building a frequency source with programable amplitude

### ISSUE THREAD

**Issue by TianTaz** [RedPitaya/RedPitaya#153]
We are currently working on building a waveform generator to output a sine wave pulse (pulse duration up to 1 sec) up to 1MHz with a programmable amplitude. We have been trying to use scpi server for communication with RP via MATLAB by implement our entire pulse as a single cycle (in the arbitrary waveform generator mode). 
The current issue that we are facing is that the buffer size 16k does not provide enough sampling points over the pulse duration for longer than a few millisecond. 
Is there a simple way of extending the buffer size or another approach to fulfill the task? 
Thanks a lot in advance.

**Comment by b-swat** [comment]
This is not possible in the current implementation.
In any case, finalization of the FPGA together with the DMA mode will be required.
Is the issue still open or will I close the thread?
