### ISSUE TITLE
Run stops direclty

### ISSUE THREAD

**Issue by axrold** [RedPitaya/RedPitaya#156]
Hi,

I tried controlling the slow output values but when I run the python script my run automatically stops and then I don't have time to measure if the output voltages have been modified with a voltmeter. Yet I just copy and paste the analog_outputs.py and redpitaya_scpi.py, so I really don't understand where the problem come from. Any help would be very appreciated.

Thank you.

**Comment by SokolovaIrina** [comment]
Script sets output voltage for slow analog outputs.
Voltage values are command line parameters:
python analog_outputs.py AO0 AO1 AO2 AO3
Default values are 1.
