### ISSUE TITLE
Production Test: after sleep [ $? -ne 0 ] always true

### ISSUE THREAD

**Issue by iljabek** [RedPitaya/RedPitaya#158]
after `sleep` `[ $? -ne 0 ]` is always true, parts of the results the test may be obscured

e.g. but also in [more lines](https://github.com/RedPitaya/RedPitaya/search?q=%22-ne+0+%5D%22&unscoped_q=%22-ne+0+%5D%22)

https://github.com/RedPitaya/RedPitaya/blob/b18903993c15c9a69818ef9039f9cb41704493f4/Test/production/calibration_script.sh#L72-L74

**Comment by SokolovaIrina** [comment]
We have fixed this bug.
