### ISSUE TITLE
/opt/redpitaya/www/apps is a Read-only file system

### ISSUE THREAD

**Issue by AndreasJochum** [RedPitaya/RedPitaya#162]
3.2.1.2. Creating first app

$ cd /opt/redpitaya/www/apps
$ cp -r /root/RedPitaya/Examples/web-tutorial/1.template ./myFirstApp
$ cd myFirstApp

root@rp-f05676:/opt/redpitaya/www/apps# cp -r /root/RedPitaya/Examples/web-tutorial/1.template ./myFirstApp1
cp: cannot create directory './myFirstApp1': Read-only file system

OS version 0.98-694

**Comment by martirius** [comment]
You probably forgot to type the command 'rw'

**Comment by AndreasJochum** [comment]
Got it: after updating the file system reverted back to read-only
