### ISSUE TITLE
Problem Connecting red pitaya to internet 

### ISSUE THREAD

**Issue by ssooffiiaannee** [RedPitaya/RedPitaya#164]
I'm in windows 10. I wired Red pitaya directly to my PC. I load the Red Pitaya OS of the Red Pitaya website, I can access it from the web browser, but when I try to (for example) access the application marketplace, this message appears :

"RedPitaya is offline and cannot access the server! Please follow quick start instructions to put it online.", I went through the quick start instructions, I did the additional settings about Ip address, but it's still not working.

**Comment by waqarrashid33** [comment]
You seem to have the same problem as I am having #165 
Me too can access it from my browser but can't make it to connect to server.
Can you ping external IPs from the ssh terminal?

**Comment by SokolovaIrina** [comment]
Hello @ssooffiiaannee, please let us know if the issue is still actual on your side. Have you tried to implement any actions offered by waqarrashid33? 

By now we haven't been able to reproduce the issue you describes on our end. Is it possible to provide us with some video or screenshots? In case we miss anything and can have a full image with the help of screenshots/video. Thank you in advance.

**Comment by fossum** [comment]
I think I might have the same issue. The web interface seems fine and I can ping google.com from the terminal, but I cannot use the OS Update.

Side note: The link for help is broken. Currently it points to http://redpitaya.com/quick-start/
Version: STEMlab_125-xx_OS_1.04-9_stable
![image](https://user-images.githubusercontent.com/448582/149087700-dfceb20f-2a0d-43e3-b0be-4bb9fbaed0c7.png)
```
root@rp-f008ae:~# ping google.com
PING google.com (142.251.33.110) 56(84) bytes of data.
64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=1 ttl=118 time=14.4 ms
64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=2 ttl=118 time=14.3 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 14.313/14.365/14.418/0.130 ms
root@rp-f008ae:~#
```

**Comment by ssooffiiaannee** [comment]
Hello, The problem with this is that I wired the red pitaya directly to my PC, I wired it to my router and it worked.

**Comment by fossum** [comment]
Might not be a bad idea to close your issue for others.

**Comment by wa2zkd** [comment]
> I think I might have the same issue. The web interface seems fine and I can ping google.com from the terminal, but I cannot use the OS Update.
> 
> Side note: The link for help is broken. Currently it points to http://redpitaya.com/quick-start/ Version: STEMlab_125-xx_OS_1.04-9_stable ![image](https://user-images.githubusercontent.com/448582/149087700-dfceb20f-2a0d-43e3-b0be-4bb9fbaed0c7.png)
> 
> ```
> root@rp-f008ae:~# ping google.com
> PING google.com (142.251.33.110) 56(84) bytes of data.
> 64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=1 ttl=118 time=14.4 ms
> 64 bytes from sea30s10-in-f14.1e100.net (142.251.33.110): icmp_seq=2 ttl=118 time=14.3 ms
> ^C
> --- google.com ping statistics ---
> 2 packets transmitted, 2 received, 0% packet loss, time 1001ms
> rtt min/avg/max/mdev = 14.313/14.365/14.418/0.130 ms
> root@rp-f008ae:~#
> ```

Is the bad link thing real or will it be fixed

**Comment by parkerlreed** [comment]
This is wired to router and still doesn't work.

![image](https://user-images.githubusercontent.com/841440/150667137-9e9c728b-13d4-4474-90e0-d63987234102.png)

![image](https://user-images.githubusercontent.com/841440/150667148-e46d236e-2319-4bb9-9d0b-39f721fddd0a.png)

```
root@rp-f04ab3:~# ping google.com
PING google.com (142.250.68.14) 56(84) bytes of data.
64 bytes from lax17s44-in-f14.1e100.net (142.250.68.14): icmp_seq=1 ttl=114 time=77.1 ms
64 bytes from lax17s44-in-f14.1e100.net (142.250.68.14): icmp_seq=2 ttl=114 time=73.4 ms
64 bytes from lax17s44-in-f14.1e100.net (142.250.68.14): icmp_seq=3 ttl=114 time=73.8 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 73.422/74.808/77.193/1.693 ms
```

**Comment by parkerlreed** [comment]
And yeah the getting started link is dead

**Comment by fossum** [comment]
@parkerlreed, did you manually upgrade to the latest firmware? That fixed my update issue.

**Comment by parkerlreed** [comment]
@fossum link?

**Comment by crtvalentincic** [comment]
The latest OS releases can be downloaded from here: https://redpitaya.readthedocs.io/en/latest/quickStart/SDcard/SDcard.html#upgrading-red-pitaya-software

**Comment by parkerlreed** [comment]
Thanks. That is indeed working. Now to regrab everything :)
