### ISSUE TITLE
.config file for linux kernel downloaded from redpitaya website

### ISSUE THREAD

**Issue by wickywaka** [RedPitaya/RedPitaya#181]
For compiling modules or checking the kernel configurations we need a .config file.
Its normally located at /proc/config.gz or in the /boot directory. Recently I downloaded an image from redpitaya and it doesn't contain these. Its probably disable as in the case for most embedded linux.
Does anyone knows how to get it?

**Comment by adrien-mars** [comment]
In my impression, 
.config file is normally located at Linux Kernel source code folder, such as linux-xlnx-branch-redpitaya-v2017.2
