### ISSUE TITLE
STEMlab122.88 wrong frequency using the Signalgenerator and FFT 

### ISSUE THREAD

**Issue by fsteinbacher** [RedPitaya/RedPitaya#187]
This HW Version use a Masterclock of 122.88Mhz, but it seems the SW calculates with 125.0Mhz. Most of the frequency related functions, like signalgenerator, or FFT display are wrong by the factor of 122.88/125.00.

**Comment by Jaimenms** [comment]
Does this issue affect the Python API?

**Comment by fsteinbacher** [comment]
Scripts using the SCPI Interface are affected.

**Comment by b-swat** [comment]
Fixed
