### ISSUE TITLE
Line Endings in SynChechk.sh have wrong format

### ISSUE THREAD

**Issue by iAnyKey** [RedPitaya/RedPitaya#188]
Line endings in [synCheck.sh](/RedPitaya/RedPitaya/blob/master/fpga/synCheck.sh) are specified in Windws Format (CR+LF) instead of Unix(LF), which makes the file unusable on linux.
how to fix: edit in Notepad++ -> edit -> format line ending -> UNIX -> save

**Comment by SokolovaIrina** [comment]
I have checked synCheck.sh and it's in the correct Unix format (LF).
