### ISSUE TITLE
Where can I download an old version of SD card image? I need 0.94

### ISSUE THREAD

**Issue by shuow2** [RedPitaya/RedPitaya#197]

**Comment by b-swat** [comment]
Hey.
0.94 is this probably a version of the FPGA?
If you said from what date the assembly would be a little easier.
Or look here:
http://downloads.redpitaya.com/downloads/
there are very old builds.

**Comment by shuow2** [comment]
Hi,

I am using "impedance analyzer" application. The version information is as following. The assembly date might be 12/21/2015 or so.

[cid:ca4d0074-1e3f-462f-8d09-97fa0974231c]

Thanks so much for your help!

Best,
Lillian

________________________________

**Comment by b-swat** [comment]
I uploaded old ecosystem images. Maybe you will find the right one.
http://downloads.redpitaya.com/downloads/0.92-0.94%20old%20ecosystems/

**Comment by shuow2** [comment]
Hi,

Thanks for your reply. But it seems they cannot be downloaded...Could you please help fix it?

[cid:43818121-6aac-4ae1-969a-dca860b2c5e1]
Thanks,
Lillian
________________________________

**Comment by b-swat** [comment]
I fixed the permissions.
Check out
