### ISSUE TITLE
Plotting Real Time Data with Python

### ISSUE THREAD

**Issue by jgomezcic** [RedPitaya/RedPitaya#202]
Hello everyone.

I have been working with this module:

```
#!/usr/bin/python

import sys
import redpitaya_scpi as scpi
import matplotlib.pyplot as plot

rp_s = scpi.scpi(sys.argv[1])

rp_s.tx_txt('ACQ:START')
rp_s.tx_txt('ACQ:TRIG NOW')

while 1:
    rp_s.tx_txt('ACQ:TRIG:STAT?')
    if rp_s.rx_txt() == 'TD':
        break

rp_s.tx_txt('ACQ:SOUR1:DATA?')
buff_string = rp_s.rx_txt()
buff_string = buff_string.strip('{}\n\r').replace("  ", "").split(',')
buff = list(map(float, buff_string))

plot.plot(buff)
plot.ylabel('Voltage')
plot.show()

```

But I would like to know if there is a way to plotting data in real time much like the native "Oscilloscope & Signal Generator application" does in python.

**Comment by bisen2** [comment]
This is more of a Python question than anything related to the Red Pitaya. Matplotlib provides an [animation module](https://matplotlib.org/3.3.3/api/animation_api.html) that should help with what you want to do. Essentially, you will define a function that gets the current data and calls `plt.plot()` and pass this function to the `matplotlib.animation.FuncAnimation(...)` method, which will call your function repeatedly. [Here is a good example of using this module.](https://pythonprogramming.net/live-graphs-matplotlib-tutorial/)
