### ISSUE TITLE
Ubuntu base URL broken

### ISSUE THREAD

**Issue by tobias-roehmel** [RedPitaya/RedPitaya#203]
I had trouble using the OS/debian/image.sh script. After some digging, I found that the UBUNTU_BASE_URL (http://cdimage.ubuntu.com/ubuntu-base/releases/16.04.3/release/ubuntu-base-16.04.3-base-armhf.tar.gz)
in OS/debian/ubuntu.sh didn't work for me. 
I changed UBUNTU_BASE_VER to 16.04.6 and the script seems to work now.

**Comment by adrien-mars** [comment]
yes, I had the same problem and solution，at present, there are no problems with this solution
