### ISSUE TITLE
Logrotate for Nginx logs

### ISSUE THREAD

**Issue by stephtr** [RedPitaya/RedPitaya#208]
When leaving our RedPitayas running for a longer period of time, we already had multiple cases where there was no space left on the SD card, since Nginx's log files grew to a file size of multiple GBs. Would it make sense to use logrotate in the stock firmware to get rid of old log portions?

**Comment by b-swat** [comment]
I redid the mount methods. Logs are now stored in memory on the virtual file system and do not take up space on the memory card.

**Comment by stephtr** [comment]
Sounds perfect, thanks!
