### ISSUE TITLE
Add Ext CAN support 

### ISSUE THREAD

**Issue by ArthurMargerit** [RedPitaya/RedPitaya#220]
The current soft failed to decode, in the web app, the CAN protocol if it's 29 bits identification.

ISO 11898 part A → CAN 2.0A « standard frame format » (identification sur 11 bits) .
ISO 11898 part B → CAN 2.0B « extended frame format » (identification sur 29 bits).

**Comment by b-swat** [comment]
I tested, it worked for me with extended CAN headers
