### ISSUE TITLE
Updater app uses "STEM 14" instead of "STEM 250 12"

### ISSUE THREAD

**Issue by deceptiveSimplicity** [RedPitaya/RedPitaya#242]
https://github.com/RedPitaya/RedPitaya/blob/a6404e7b9913a59c0779c7353327053de45e0dba/apps-tools/updater/nginx.conf#L171

On my SIGNALlab 250-12 v1.1 the hw_rev env var is "STEM_250-12_V1.1" - note the capital V. The string compare seems to be case sensitive, evaluating to false in my case. That's why the updater app uses the default value "STEM 14" to query for updates.

**Comment by b-swat** [comment]
@deceptiveSimplicity Thanks a lot. I will consider this bug in the next version.
