### ISSUE TITLE
Pure signal option

### ISSUE THREAD

**Issue by PittG** [RedPitaya/RedPitaya#243]
Hello

   Can anyone tell me where just the correction of signal value in "pure signal" procedure is done : in Red Pitaya fpga hardware or in PC software.  I know generally block diagram for "pure signal" procedure, but I'd like to know where exactly value of signal is adjusted to minimal IMD.

Thanks in advance,
PittG

**Comment by b-swat** [comment]
Hello
At 0.94 fpga, the signal is filtered, and the signal is calibrated on the software side. No additional conversions take place.

**Comment by PittG** [comment]
Thank You for information.

All the best,
PittG
