### ISSUE TITLE
xdc on Vivado 2014.4

### ISSUE THREAD

**Issue by qermit** [RedPitaya/RedPitaya#25]
Need change IOSTANDARD for XADC pins to LVCMOS33 to generate bitstream using Vivado 2014.4

**Comment by HrRossi** [comment]
The supported version of Vivado - at the moment - is 2013.3. 
Changing the IOSTANDARD for the XADC breaks the build on 2013.3, I already tried it. 
So, you are of course free to change it for your project, but as long as the RP project is built on 2013.3 this will not be changed.
