### ISSUE TITLE
RedPitaya OS 2.0 not booting on 125-14

### ISSUE THREAD

**Issue by richtoy** [RedPitaya/RedPitaya#250]
Hi,

I am trying to get the new 2.0 version working but it refuses to boot.

I have tried with both a used 8G and a brand new Kingston CANVAS Select Plus 32G SD cards and the results are the same.  Burn successfully with balenaEtcher-Portable-1.18.4.  Place in RedPitays 125-14 and apply power.  Green light burns and yellow light burns very dimmly.  Meanwhile 1.04-28 runs fine.

Is there anything else to try?

Kindest regards,

**Comment by b-swat** [comment]
Good day. Check which board model is listed in eeprom?
Take the 1.04-28 ecosystem and run the **fw_printenv** command in the console

**Comment by richtoy** [comment]
As requested

***@***.***:~# fw_printenv
bootcmd=run $modeboot
bootdelay=3
baudrate=115200
ipaddr=10.10.70.102
serverip=10.10.70.101
prod_date=12/22/13
kernel_image=uImage
ramdisk_image=uramdisk.image.gz
devicetree_image=devicetree.dtb
bitstream_image=system.bit.bin
loadbit_addr=0x100000
kernel_size=0x500000
devicetree_size=0x20000
ramdisk_size=0x5E0000
fdt_high=0x20000000
initrd_high=0x20000000
sdboot=echo Copying Linux from SD to RAM... && mmcinfo && fatload mmc 0
0x3000000 ${kernel_image} && fatload mmc 0 0x2A00000 ${devicetree_image} &&
fatload mmc 0 0x2000000 ${ramdisk_image} && bootm 0x3000000 0x2000000
0x2A00000
ethaddr=00:26:32:F0:0F:0E
nav_code=4662
hw_rev=1.1
serial=142400850
***@***.***:~#

Kindest regards,
Richard Toy

**Comment by richtoy** [comment]
This is the console output for the image that fails to boot:

Zynq> ▒

U-Boot 2022.01 (Mar 06 2023 - 16:24:17 +0000), Build:
jenkins-redpitaya-master-unify-15

CPU:   Zynq 7z010
Silicon: v3.1
DRAM:  ECC disabled 512 MiB
Flash: 0 Bytes
NAND:  0 MiB
MMC:   ***@***.***: 0
Loading Environment from nowhere... OK
In:    ***@***.***
Out:   ***@***.***
Err:   ***@***.***
Net:
ZYNQ GEM: e000b000, mdio bus e000b000, phyaddr 1, interface rgmii-id
eth0: ***@***.***
Hit any key to stop autoboot:  0
Running script from SD...
Device: ***@***.***
Manufacturer ID: 27
OEM: 5048
Name: SD32G
Bus Speed: 50000000
Mode: SD High Speed (50MHz)
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 28.8 GiB
Bus Width: 4-bit
Erase Group Size: 512 Bytes
3302 bytes read in 14 ms (229.5 KiB/s)
## Executing script at 02000000
Setting bus to 0

EEPROM @0x50 read: addr 0x00000000  off 0x1800  count 1024 ... done
Set devicetree and ramdisk high loading address to 0x20000000
Loading from SD card (FAT file system) to memory
Device: ***@***.***
Manufacturer ID: 27
OEM: 5048
Name: SD32G
Bus Speed: 50000000
Mode: SD High Speed (50MHz)
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 28.8 GiB
Bus Width: 4-bit
Erase Group Size: 512 Bytes
Load uImage
5655072 bytes read in 323 ms (16.7 MiB/s)
Load dts//devicetree.dtb
Failed to load 'dts//devicetree.dtb'
Booting Linux kernel with ramdisk and devicetree
## Booting kernel from Legacy Image at 02004000 ...
   Image Name:   Linux-5.15.0-xilinx
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5655008 Bytes = 5.4 MiB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
Zynq>

Kindest regards,
Richard Toy

**Comment by b-swat** [comment]
I see you have an incorrect version of the board specified in the eeprom.
I don't know how it happened, but there should be a line like: hw_rev=STEM_125-14_v1.1

You can change it yourself, to the correct version.
To do this, you need to boot from a working image.

1) Connect TP1A to ground. This is necessary to open the protected area of the eeprom for writing.
![IMG_7733](https://user-images.githubusercontent.com/41248006/227450529-fd818c21-2783-4f74-a71b-f8793c362bee.jpeg)
2) Through the console, put the correct model
root@rp-f01c3d:~# fw_setenv hw_rev STEM_125-14_v1.1 
3) Check with fw_printenv that the value has been applied.
4) Run with a new image

PS.
The [script](https://github.com/RedPitaya/RedPitaya/blob/master/patches/u-boot/u-boot.script) for loading the board configuration can be found here. You can check if the model matches the board.
Other boards are not supported.

**Comment by richtoy** [comment]
Worked as explained.  Thanks!

[image: image.png]

**Comment by wkumari** [comment]
I also had this issue - my env were:
```
root@rp-f017d1:~# fw_printenv
bootcmd=run $modeboot
bootdelay=3
baudrate=115200
ipaddr=10.10.70.102
serverip=10.10.70.101
prod_date=12/22/13
kernel_image=uImage
ramdisk_image=uramdisk.image.gz
devicetree_image=devicetree.dtb
bitstream_image=system.bit.bin
loadbit_addr=0x100000
kernel_size=0x500000
devicetree_size=0x20000
ramdisk_size=0x5E0000
fdt_high=0x20000000
initrd_high=0x20000000
sdboot=echo Copying Linux from SD to RAM... && mmcinfo && fatload mmc 0 0x3000000 ${kernel_image} && fatload mmc 0 0x2A00000 ${devicetree_image} && fatload mmc 0 0x2000000 ${ramdisk_image} && bootm 0x3000000 0x2000000 0x2A00000
ethaddr=00:26:32:F0:17:D1
nav_code=4662
hw_rev=1.1.2
serial=155000063
```

I wasn't sure what to make the `hw_rev`, so I looked at the script and chose `STEM_125-14_v1.1` - I have no idea if this was the correct one to choose, but it *does* now boot...

Perhaps updating the image, or at least the documentation would help?

**Comment by steve-moorby** [comment]
Me too...  I also have
hw_rev=1.1.2

Seems wrong to say I have the wrong value for 'hw_rev', the board has had this value since it was manufactured. 
Isn't the problem the script is not dealing with all the values of 'hw_rev' that are out there.

**Comment by b-swat** [comment]
> Me too... I also have hw_rev=1.1.2
> 
> Seems wrong to say I have the wrong value for 'hw_rev', the board has had this value since it was manufactured. Isn't the problem the script is not dealing with all the values of 'hw_rev' that are out there.

1.1.2 - These are old boards; at that time there was no standard for the hv_rev parameter.
I also admit the human factor in production.

Here are the valid versions at which the board will boot.
https://github.com/RedPitaya/RedPitaya/blob/master/patches/u-boot/u-boot.script
If you have chosen the correct Zynq version of course.

**Comment by b-swat** [comment]
Now all boards are marked with versions. If there is no such marking, then most likely you have the version: STEM_125-10_v1.0

![IMG_8951](https://github.com/RedPitaya/RedPitaya/assets/41248006/0d37b13b-406b-4c88-adea-658d28933ea0)

**Comment by steve-moorby** [comment]
For me hw_rev=1.1.2 the board shows V1.1
![IMG20231220101153](https://github.com/RedPitaya/RedPitaya/assets/52490160/8ef42246-fb74-4ef8-84f6-f75aa89e9c52)

I can see that changing hw_rev to STEM_125-14_v1.0 gets the board to boot but are you saying that V1.1 is completely compatible with STEM_125-14_v1.0 or are you saying that V1.1 is not supported with OS 2.0 ?

**Comment by b-swat** [comment]
boards 125-14 and 125-10 are fully compatible, the revision version does not affect the functionality.
any revision can be specified

**Comment by steve-moorby** [comment]
Thanks for that.  So changing hw_rev to STEM_125-14_v1.0 is just bringing an older board in line with newer version conventions.

**Comment by tthulesius** [comment]
> I see you have an incorrect version of the board specified in the eeprom. I don't know how it happened, but there should be a line like: hw_rev=STEM_125-14_v1.0
> 
> You can change it yourself, to the correct version. To do this, you need to boot from a working image.
> 
> 1. Connect TP1A to ground. This is necessary to open the protected area of the eeprom for writing.
>    ![IMG_7733](https://user-images.githubusercontent.com/41248006/227450529-fd818c21-2783-4f74-a71b-f8793c362bee.jpeg)
> 2. Through the console, put the correct model
>    root@rp-f01c3d:~# fw_setenv hw_rev STEM_125-14_v1.0

Im trying to find TP1A on my version V1.1-board

I have found TP1 but not TP1A.....

Please advice / Tilman

**Comment by b-swat** [comment]
@tthulesius  Maybe the name is a little different. The point must be in the same place

**Comment by UnePierre** [comment]
@tthulesius, But you found it in the 960x1280 photo of @b-swat at pixel coordinates (360,765)?

**Comment by igel1** [comment]
Followed your instruction - seems that I destroyed my redpitaya ...

That's what I have done 
(I logged in via ssh and run the fw_setenv command while TP1A was connected to ground):

```
ssh root@rp-f006bb.local
The authenticity of host 'rp-f006bb.local (192.168.63.157)' can't be established.
ED25519 key fingerprint is SHA256:1ePh1yiwMLPu2i+N+1GLSfZAyC6soezYyImuI9ZaiQ4.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'rp-f006bb.local' (ED25519) to the list of known hosts.
root@rp-f006bb.local's password:
Permission denied, please try again.
root@rp-f006bb.local's password:
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.9.0-xilinx armv7l)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
##############################################################################
# Red Pitaya GNU/Linux Ecosystem
# Version: 1.04
# Build: 18
# Branch:
# Commit: 27498667c96692b6f15a7878462480c66c6c0abf
# U-Boot: "redpitaya-v2016.4"
# Linux Kernel: "branch-redpitaya-v2017.2"
# Pro Applications: ""
##############################################################################
Last login: Thu Aug 22 20:28:28 2024
root@rp-f006bb:~# fw_printenv
bootcmd=run $modeboot
bootdelay=3
baudrate=115200
ipaddr=10.10.70.102
serverip=10.10.70.101
prod_date=12/22/13
kernel_image=uImage
ramdisk_image=uramdisk.image.gz
devicetree_image=devicetree.dtb
bitstream_image=system.bit.bin
loadbit_addr=0x100000
kernel_size=0x500000
devicetree_size=0x20000
ramdisk_size=0x5E0000
fdt_high=0x20000000
initrd_high=0x20000000
sdboot=echo Copying Linux from SD to RAM... && mmcinfo && fatload mmc 0 0x3000000 ${kernel_image} && fatload mmc 0 0x2A00000 ${devicetree_image} && fatload mmc 0 0x2000000 ${ramdisk_image} && bootm 0x3000000 0x2000000 0x2A00000
ethaddr=00:26:32:F0:06:BB
nav_code=4662
hw_rev=1.1
serial=141600719
root@rp-f006bb:~# fw_setenv hw_rev STEM_125-14_v1.1
root@rp-f006bb:~# fw_printenv
Warning: Bad CRC, using default environment
*** Error in `fw_printenv': malloc(): memory corruption: 0x00027410 ***
Aborted
root@rp-f006bb:~# fw_printenv
Warning: Bad CRC, using default environment
*** Error in `fw_printenv': malloc(): memory corruption: 0x00027410 ***
Aborted
root@rp-f006bb:~# fw_setenv hw_rev STEM_125-14_v1.1
Warning: Bad CRC, using default environment
## Error: environment not terminated
## Error: environment not terminated
*** Error in `fw_setenv': malloc(): memory corruption: 0x00027410 ***
Aborted
root@rp-f006bb:~# Shared connection to rp-f006bb.local closed.```

What can I do now?

Best regards

A.

**Comment by Lightsaver7** [comment]
Hello @igel1,

Please write to support@redpitaya.com mentioning this issue. We start an RMA process to fix the corrupted EEPROM.

**Comment by igel1** [comment]
> Hello @igel1,
> 
> Please write to [support@redpitaya.com](mailto:support@redpitaya.com) mentioning this issue. We start an RMA process to fix the corrupted EEPROM.

Thank you Lightsaver7 - that's very kind of you.
I felt really desperate after this happened to me - you saved my day!
(although I followed your instructions very carefully - how can that happen?)

I will report here how things go on ...

Kind regards

Igel1

**Comment by Lightsaver7** [comment]
I am not 100% sure how an EEPROM corruption could have happened, but driving the TP1A low enables writing inside the EEPROMs protected area, which may have played a part in the corruption.
Don't worry, we will fix the board.

Best regards,
Ligthsaver7

**Comment by Lightsaver7** [comment]
> @tthulesius, But you found it in the 960x1280 photo of @b-swat at pixel coordinates (360,765)?

Yes, TP1A is the golden circle located at those coordinates. It's located in the "V" formed by the E2 connector and the black cooler in the middle, as shown in the picture below.
![227450529-fd818c21-2783-4f74-a71b-f8793c362bee](https://github.com/user-attachments/assets/f5bcddce-876e-4790-9581-28d148a45c65)

**Comment by igel1** [comment]
Huh - in the RMA form I read:

"Return requests will be processed on the receipt of a completed RMA form only.

Defect items being under warranty will be repaired or replaced free of charge. For out of warranty items the repair or replacement will be invoiced accordingly. After receiving the defective items & confirmation by email diagnostic the current price is 50 EUR and separately repair price is 120 EUR.

By submitting this form you agree with the above-mentioned terms and conditions of the RMA process."

My RedPitaya is out of warranty and I do not have the invoice any more.
Does that mean you will charge me 50€ + 120€ to fix the EEPROM?

Kind regards

A.

**Comment by Lightsaver7** [comment]
Dear @igel1,

I have consulted with the team. The RMA form is out of date (and the text is now fixed). Please be assured that there is no additional charge for repairing the board. As per RMA terms, you will have to pay for the shipping to us. We will pay for shipping back to you. 

We no longer repair boards that are out of warranty. Your case is an exception as the memory corruption occurred while you were following our instructions and it does not require hardware replacement.

Best regards,
Lightsaver7

**Comment by igel1** [comment]
@Lightsaver7:  that's really nice and fair of you (and your colleagues/company)!
I will fill out the form and send you the board in the next few days.

Kind regards
A.

**Comment by steve-embling** [comment]
```
hw_rev=1.0
serial=140800414
```

Also failing an update - will I get these RMA terms if I update the revision too?

**Comment by igel1** [comment]
> @Lightsaver7: that's really nice and fair of you (and your colleagues/company)! I will fill out the form and send you the board in the next few days.

Got back my RedPitaya yesterday (the whole process was delayed due to me being on holiday) 
... and ... yipheee ... it works!

They have been so kind to flash the latest hw_rev=STEM_125-14_v1.1 into my eeprom,
so I can run version 2 Images now (tried 2.04-35 - it went out of the box).

Everything perfect - I am so happy and gratefull to the staff at RedPitaya, they made a great repair job!
(... and - by the way - communication was also perfect: every email I sent was answered immediately ...)
A big thank you from my side and a big thumbs up.

Kind regards

Igel1

**Comment by Lightsaver7** [comment]
> ```
> hw_rev=1.0
> serial=140800414
> ```
> 
> Also failing an update - will I get these RMA terms if I update the revision too?

Hello @steve-embling,

Please send us the board and we will update the "hw_rev" number for you. The terms are the same as for igel1 (you pay the shipping to us, we pay the shipping back to you, the repair service is free). This particular issue is an exception to the RMA process, where we will repair out-of-warranty boards. Please write to support@redpitaya.com so that we can start the RMA process.

We will offer the terms described in this message to anyone that wants to update the "hw_rev" number.

**Comment by kng** [comment]
To add to a pretty thorough thread, I have a old v1.1 board that boots the 1.0 OS just fine.
it had the `hw_rev=1.1.2` and I had a go at modifying the u-boot.scr and almost got it up and running on OS 2.05-37.
to fix it permanently I did this:
interrupt the u-boot and get the prompt `Zynq>`
show the env with `printenv` and make sure it has read: hw_rev serial ethaddr
set the hw_rev to the newer style: `setenv hw_rev STEM_125-14_v1.0`
ground the TP1A before saving the contents to eeprom with `saveenv`
reset and OS 2.x should boot just fine.

it might be safer to run this under the old OS 1.x u-boot, not sure.

if the values show up as 0, try reading them manually from eeprom:
```
i2c dev 0
eeprom read  0 0x50 0 0x1804 0x400
env import -b 0 0x400 hw_rev serial ethaddr
```

**Comment by Lightsaver7** [comment]
> Hello [@steve-embling](https://github.com/steve-embling),
> 
> Please send us the board and we will update the "hw_rev" number for you. The terms are the same as for igel1 (you pay the shipping to us, we pay the shipping back to you, the repair service is free). This particular issue is an exception to the RMA process, where we will repair out-of-warranty boards. Please write to [support@redpitaya.com](mailto:support@redpitaya.com) so that we can start the RMA process.
> 
> We will offer the terms described in this message to anyone that wants to update the "hw_rev" number.

We strongly advise against attempting to repair the boards yourself, especially if you lack expertise in electronics.

For those considering undertaking this procedure independently, please exercise extreme caution during the process. Any negligence could result in an electrostatic discharge (ESD), which may damage the EEPROM chip and further compromise the board's functionality. A burned EEPROM leads to Red Pitaya reporting memory corruption issues. We kindly request that you review the following article before proceeding: https://www.michelli.com/how-to-protect-your-electronics-from-electrostatic-discharge-esd/.

**Comment by ghpille** [comment]
Perhaps the developers could update the Bazaar software and the u-boot.scr to take into account the existence of hw_rev 1.1 and 1.1.2?  It would avoid risky eeprom manipulations or redpitayas getting lost in the post.

**Comment by pe1pip** [comment]
Any update on this? I've got a 2016 original RP hw rev 1.1.2 and a 2019 122-16, neiter will boot the latest firmware and I'm not keen on fixing the hw_rev in the firmware, especially because I'm not sure what to set it to.

**Comment by b-swat** [comment]
> Any update on this? I've got a 2016 original RP hw rev 1.1.2 and a 2019 122-16, neiter will boot the latest firmware and I'm not keen on fixing the hw_rev in the firmware, especially because I'm not sure what to set it to.

Hello. I was making changes to the pre-release version so that the RP would boot if it failed to detect the board model. But it defaults to loading as 125-14 v1.1. If there is an issue with the 122-16, it won't work on that board. In any case, the board model in the EEPROM needs to be fixed.

https://downloads.redpitaya.com/downloads/Unify/nightly_builds/
check readme https://downloads.redpitaya.com/downloads/Unify/nightly_builds/README.txt

**Comment by ghpille** [comment]
There's no need for any "fixing" but that Redpitaya would add the early models to their code. 

B-swat85 ***@***.***> schreef op 30 mei 2026 04:36:51 CEST:

**Comment by Lightsaver7** [comment]
Here is the list of board IDs:
https://github.com/RedPitaya/RedPitaya/blob/master/rp-api/api-hw-profiles/src/common.cpp#L184

For SDRlab I recommend using the 1.0 version on the link above

**Comment by Lightsaver7** [comment]
> There's no need for any "fixing" but that Redpitaya would add the early models to their code.
> 

Unfortunately, this is impossible since the issue affects multiple board models (all of which use the same hw_id). While most of the affected boards are STEMlab 125-14, there are other models in the mix, such as SDRlab 122-16, which users have recently reported with the same hw_id. This means the code cannot distinguish between them.

In the upcoming 3.00 release, we decided that should an incorrect hw_id be detected, the boot will default to STEMlab 125-14.

**Comment by pe1pip** [comment]
> Here is the list of board IDs: https://github.com/RedPitaya/RedPitaya/blob/master/rp-api/api-hw-profiles/src/common.cpp#L184
> 
> For SDRlab I recommend using the 1.0 version on the link above

What I can't quite oversee is that my original Red Pitaya, which now reports '1.1.2' maps to this table. I'm guessing that "STEM_125-14_v1.1" is okay, because that matches the version number on the PCB. 

As for my 122-16, that reports "hw_rev=STEM_122-16SDR_v1.1" which is in the table, so I'm wondering why it's not booting the latest 2.0 image. I'll have to dig in somewhat more.

**Comment by b-swat** [comment]
> > Here is the list of board IDs: https://github.com/RedPitaya/RedPitaya/blob/master/rp-api/api-hw-profiles/src/common.cpp#L184
> > For SDRlab I recommend using the 1.0 version on the link above
> 
> What I can't quite oversee is that my original Red Pitaya, which now reports '1.1.2' maps to this table. I'm guessing that "STEM_125-14_v1.1" is okay, because that matches the version number on the PCB.
> 
> As for my 122-16, that reports "hw_rev=STEM_122-16SDR_v1.1" which is in the table, so I'm wondering why it's not booting the latest 2.0 image. I'll have to dig in somewhat more.

https://redpitaya.readthedocs.io/en/latest/developerGuide/software/getting_started/console/console.html
Check the board's boot log in the console. This will show you where it stops booting.
