### ISSUE TITLE
SPI CS inverted using RP hardware API

### ISSUE THREAD

**Issue by HB9GKW** [RedPitaya/RedPitaya#251]
The RP hardware API for SPI (rp_hw.h) is turning chip select line to be active high instead of active low, which should be the default setting. As there is no option to invert CS polarity, most SPI slaves will not work that way. There are two example applications located under /Examples/C/ that demonstrate opposite CS polarity behavior:

- spi_loopback.c
  using RP HW API (rp_hw.h) -> active high CS

- spi.c
  using Linux SPI (linux/spi/spidev.h and sys/ioctl.h) -> active low CS

During system boot the RP defaults to active low (high idle) CS state, which is fine. However after running spi_loopback application once, CS state stays permanently low even after calling function rp_SPI_Release().

**Comment by b-swat** [comment]
The bug was still there. He really after sending the last message changed the state to the opposite of the default.
I removed this code. I will also add a default state for CS. In the current version of the api, it always defaulted to the HIGH state

**Comment by HB9GKW** [comment]
Thank you that's great! So you mean in the current version of the api but using old ecosystem and kernel 4.9, CS defaulted to high?

**Comment by b-swat** [comment]
In the new version, the default state is also HIGH when the board is loaded. I will add documentation on how to make the default state LOW

**Comment by HB9GKW** [comment]
Yes on startup CS defaults to HIGH which is good. Just after calling rp_SPI_ReadWrite() CS goes LOW, then HIGH during data transmission and LOW afterwards.. and then stays LOW even after rp_SPI_Release(). I guess there is no fix for the meantime, beside using sys/ioctl.h and linux/spi/spidev.h directly like in example spi.c?

**Comment by b-swat** [comment]
You can check pre-released version 
https://downloads.redpitaya.com/downloads/Unify/nightly_builds/
