### ISSUE TITLE
External Trigger not working on STEMlab 125-14 4-Inputs (Red Pitaya OS 2.00-15)

### ISSUE THREAD

**Issue by HB9GKW** [RedPitaya/RedPitaya#253]
Extension connector E1 pin 3 (DIO0_P) does not trigger data acquisition on new 4-input channel version. Neither the standard scope NGINX application nor the C API works with external trigger. 
For example setting trigger source to rp_AcqSetTriggerSrc(RP_TRIG_SRC_EXT_PE) and toggling DIO0_P pin while polling trigger state with rp_AcqGetTriggerState(&state) never returns RP_TRIG_STATE_TRIGGERED, even tough polling RP_DIO0_P shows that pin state is alternating.

rp_AcqReset();
rp_AcqSetGain(RP_CH_1, RP_LOW);
rp_AcqSetGain(RP_CH_2, RP_LOW);
rp_AcqSetGain(RP_CH_3, RP_LOW);
rp_AcqSetGain(RP_CH_4, RP_LOW);
rp_AcqSetDecimation(RP_DEC_1);
rp_AcqSetTriggerDelay(0);
rp_AcqStart();
usleep(135);
rp_GPIOpSetDirection(0);
rp_AcqSetTriggerSrc(RP_TRIG_SRC_EXT_PE);
rp_acq_trig_state_t state = RP_TRIG_STATE_TRIGGERED;
rp_pinState_t dio0_p_pin = RP_LOW;
rp_pinState_t dio0_p_mem = RP_LOW;
        
while(1)
{
    usleep(135);
    rp_AcqGetTriggerState(&state);
    rp_DpinGetState(RP_DIO0_P, &dio0_p_pin);
    if(dio0_p_pin != dio0_p_mem) 
    {
        printf("\nDIO0_P state:%d", dio0_p_pin);
        dio0_p_mem = dio0_p_pin;
        if(state == RP_TRIG_STATE_WAITING)
        {
            printf("\nRP_TRIG_STATE_WAITING\n");
        }
    }
    if(state == RP_TRIG_STATE_TRIGGERED)
    {
        printf("\nTRIG'D");
        break;
    }
}

>>Output:
DIO0_P state:1
RP_TRIG_STATE_WAITING

DIO0_P state:0
RP_TRIG_STATE_WAITING

DIO0_P state:1
RP_TRIG_STATE_WAITING

Seems the bug is somewhere in the oscilloscope app. I had hope that calling rp_HPInit() declared in rp_hw_profiles.h might do some magic but that function is only declared in header and not even defined in rp_hw_profiles.c. Calling this function results in compilation error "undefined reference to `rp_HPInit' collect2: error: ld returned 1 exit status".

**Comment by b-swat** [comment]
Hi.
Check last nightly build.
On my side the ext trigger is worked.
https://downloads.redpitaya.com/downloads/Unify/nightly_builds/
