### ISSUE TITLE
Why was the FPGA loading method changed in OS 2.0

### ISSUE THREAD

**Issue by MEisebitt** [RedPitaya/RedPitaya#265]
I recently upgraded from the older 1.04 OS to the new unified 2.0 OS. One thing that I noticed is that the final generation and loading of the FPGA changed. The image has to be loaded with `fpgautil` instead of `cat`'ing it into xdevcfg which is cool. However, it does not accept the old bitstream file format, but rather the file has to be converted into a binary bitstream over a few steps (BIF & bootgen). I was just wondering if there is a reason for this, as it seems a bit more work than the previous method.

**Comment by b-swat** [comment]
As I recall from 2020 vivado xdevcfg is no longer supported. xdevcfg remained as a stub.
