### ISSUE TITLE
stuck at "Getting list of applications" screen and restarts

### ISSUE THREAD

**Issue by Hermy07** [RedPitaya/RedPitaya#268]
I just tried out the last versions, Stable version (2.00-18) and Beta version (2.00-23), and stuck at the Getting list of applications screen. 
Also it seems the board resets if i am trying to connect. 
Using board 125-14 v1.0

**Comment by b-swat** [comment]
Disable ad block

**Comment by Hermy07** [comment]
unfortunately it is not the ad block and it is working with older versions like 1.4

**Comment by b-swat** [comment]
can you check fw version in eeprom?

**Comment by b-swat** [comment]
https://github.com/RedPitaya/RedPitaya/issues/254

**Comment by Hermy07** [comment]
Is there a preferred way to do this? 
Also checked the environment with printenv, but there is no hw version listed

**Comment by Hermy07** [comment]
sorry wrong command
fw_printenv: hw_rev=STEM_125-14_v1.0

**Comment by b-swat** [comment]
Try to connect the board via console/minicom. you can see if the board reboots when connected

**Comment by Hermy07** [comment]
![image](https://github.com/RedPitaya/RedPitaya/assets/76438961/db932bad-7964-40c5-a2d7-3aeabce8bfa7)

The output just after bootup and after i open the webserver in browser

**Comment by b-swat** [comment]
I've only observed two cases in all my time. The reboot can be caused by a frozen FPGA. When the FPGA is not from another board to write for example from Z7020 or to write when the FPGA registers are being accessed. The second case is when there is insufficient power supply. If the power supply is bad, then increasing the load on the processor leads to the fact that the board immediately reboots.

**Comment by arnaudrichard** [comment]
I confirm that powering RedPitaya by a PC USB or even worse through USB hub lead to spurious resets.

**Comment by Lightsaver7** [comment]
Please use the power supply you received together with the board or use a 5V DC power supply that can provide 2 Amps of current (for completely independent operation (couple of hours) you can also use phone power banks). The USB from the computer supplies the necessary voltage, but the current is too low (approx. 1.2 A on USB 3.0).

**Comment by Hermy07** [comment]
A insufficient power supply was something i thought about. I tried it with power supplies with much higher output power.
It seems like the board i used is damaged. I tried it with other v1.0 boards and it worked just fine.
