### ISSUE TITLE
LED 8 weakly lit after bootup

### ISSUE THREAD

**Issue by mikelachaine** [RedPitaya/RedPitaya#27]
LED 8 is weakly lit right after boot-up. GPIO block 0 not properly initialized.
Ref. and temporary workaround here, https://redpitaya.zendesk.com/hc/communities/public/questions/200247982-LED-8-always-on-at-50-intensity

Mine is RP v1.1 eco. 0.93-14 and this issue is still present.

**Comment by jeras** [comment]
This is a software configuration issue. In version 0.94 this led is used as SD card access indicator. LED 0 was also re-purposed from a redundant FPGA status indicator to a general purpose LED.
