### ISSUE TITLE
BIN file parse

### ISSUE THREAD

**Issue by oligofrenia** [RedPitaya/RedPitaya#289]
Hi, 
I have a problem with getting data from the BIN file. I acquire data using a streaming server. I'm trying to get up 100000 samples. In the WAV file, I have exactly 100000 samples, but when I try to get data from the BIN file I have 100329 samples with a weird waveform. I think, it can be any header or something like that in this file but I do not find information about the structure in this file in the documentation. 
![data_view](https://github.com/RedPitaya/RedPitaya/assets/62251567/6ff660c8-ee64-466e-910c-f25105959308)

**Comment by Lightsaver7** [comment]
Hello,
Thank you for letting us know. I will consult with the team regarding this and modify the docs to include this information.
If I understand correctly, you are streaming data from the Streaming application to the SD card?

**Comment by oligofrenia** [comment]
Yes, I use the Data Stream Control app from the web interface. I save the file locally (to the SD card).

**Comment by Lightsaver7** [comment]
Thanks b-swat, I'll add this to docs :D

**Comment by oligofrenia** [comment]
Great, everything works perfectly!
