### ISSUE TITLE
problem wish bash prompt

### ISSUE THREAD

**Issue by pavel-demin** [RedPitaya/RedPitaya#39]
The current version of the bash prompt does not behave well with long lines and when browsing the history with up and down arrows.

I tried to follow the instructions from [ArchWiki](https://wiki.archlinux.org/index.php/Color_Bash_Prompt). It suggests to use  `\[\e[color\]` and `\[\e[m\]` to start and to end coloring. It also says that "`\[` and `\]` should wrap non-printing characters sequences to avoid wrong estimation of PS1 size which leads to display issues when navigating through history and editing the command line".

Finally, I obtained the following result that looks the same but behaves much better:
```
export PS1="\[\e[0;31m\]red\[\e[1;31m\]pitaya>\[\e[m\] "
```

Could you please update the bash prompt configuration in `/etc/profile.d/profile.sh`?

**Comment by jeras** [comment]
Thank you very much for this fix, this issue was bothering us a lot. It will be available in the next release v0.94-RC19.
