### ISSUE TITLE
recipe for /output/build/libdaemon-0.14/.stamp_configured failed

### ISSUE THREAD

**Issue by Gulzt** [RedPitaya/RedPitaya#40]
I followed the latest install instructions and run the complete Makefile. The build gets very very far but eventually I stumble upon this error and I am clueless how to work around it. 

I made a copy of my screen for the last bit. If I can provide certain logfiles let me know.
![pitayabuild_crash](https://cloud.githubusercontent.com/assets/5236224/11193374/ac07c85a-8ca6-11e5-8462-6fdd21aed935.jpg)

**Comment by HrRossi** [comment]
The error occurs the first time the buildroot make process tries to use its copy of the target preprocessor. Maybe there is something wrong with your linaro installation ? Try to execute `./OS/buildroot/buildroot-2014.02/output/host/usr/bin/arm-linux-gnueabihf-cpp --version` from this exact situation, what's the result ?
