### ISSUE TITLE
SCPI: GPIO direction options wrong, documentation of default direction wrong

### ISSUE THREAD

**Issue by HrRossi** [RedPitaya/RedPitaya#51]
1. The documentation of scpi commands lists the DIG:PIN:DIR values as "INP" and "OUTP", but the values in scpi-server/src/dpin.c are "IN" and "OUT". Consequently, setting the direction in accordance with the docs leads to errors. 
2. The default direction after a reset is input, not output as is said in the documentation. Having high impedance as default is a good choice for GPIO, so the documentation should be changed.

**Comment by b-swat** [comment]
Fixed
