### ISSUE TITLE
SCPI: documentation of data format parameters wrong

### ISSUE THREAD

**Issue by HrRossi** [RedPitaya/RedPitaya#55]
The documentation of scpi commands lists the ACQ:DATA:FORMAT options "ASCII" and "FLOAT", but it should be "ASCII" and "BIN". Some explanation how the data is encoded in binary mode should also be added.

**Comment by sanpii** [comment]
> The binary data is 16bit little endian
> [Source](https://forum.redpitaya.com/viewtopic.php?p=4396&sid=63c1c50d87252b7d3d866089a9898625#p4396).

You can also find an example written in python here: [acq_bin_test.py](https://github.com/RedPitaya/RedPitaya/blob/master/test/scpi/acq_bin_test.py#L74)
