### ISSUE TITLE
No FPGA Sources

### ISSUE THREAD

**Issue by ghulands** [RedPitaya/RedPitaya#61]
It would be good if you made the FPGA source available as it would allow people to learn and improve upon what is already there.

**Comment by noah95** [comment]
You can find all the FPGA source files under https://github.com/RedPitaya/RedPitaya/tree/master/fpga/rtl

**Comment by ghulands** [comment]
My bad - I missed it. The readme also references this folder which is missing fpga/hsi/. Not sure if the read me is out of date

**Comment by HrRossi** [comment]
The fpga/hsi subfolder has apparently been renamed to fpga/sdk without updateing the README.
