### ISSUE TITLE
Please create a tag for version 0.95

### ISSUE THREAD

**Issue by pavel-demin** [RedPitaya/RedPitaya#67]
Dear RedPitaya developers,

The version number of the SD image zip file downloadable from redpitaya.com is 0.95.

Looking at the RedPitaya github repository, it's not clear what code is used to build this SD image zip.

Could you please create a tag corresponding to this version?

Kind regards,

Pavel

**Comment by HrRossi** [comment]
Seconded. It's been a while that 0.95 has been released for binary download, and clearly it's not been built from code in this repository.

**Comment by jeanminet** [comment]
Red Pitaya developers responded to the same question in the forum (http://forum.redpitaya.com/viewtopic.php?f=8&t=1451)

> Hi guys
Yes, GitHub repo. is not yet updated to 0.95 version.
It will be updated in month or less.
Sorry for the inconvenience.
All Best, RP

**Comment by HrRossi** [comment]
I realize that this information is helpful for anybody who might chance upon this conversation, but the fact that you quote this to the two most active users on that same forum still made me smile ;O)

**Comment by DF4IAH** [comment]
Thanks for information. This is number **three** of active developpers. May I introduce myself?   :-)

**BTW**: why are adding PR requests for the bazaar silently ignored? RadioBox is ready to
be added.

All the best also from me
  Uli, DF4IAH.

**Comment by jeras** [comment]
Hi, I was (am, will be) on a study vacation so the release procedure was a bit improvised by another coworker. I will try to prepare the sources for a release in the next few days.

**Comment by pavel-demin** [comment]
Thanks a lot for creating the [v0.95-1](https://github.com/RedPitaya/RedPitaya/tree/v0.95-1) tag!

**Comment by jeras** [comment]
Hi,

Sources are now available in a new branch:
`release-v0.95`
The tagged version will not compile properly, but with the latest commit on the branch compiling should work properly.

**Comment by DF4IAH** [comment]
Thank you very much!
