### ISSUE TITLE
ngx_http_rp_module set params infinite loop

### ISSUE THREAD

**Issue by ucgen** [RedPitaya/RedPitaya#83]
In [RedPitaya/Bazaar/nginx/ngx_ext_modules/ngx_http_rp_module/src/rp_data_cmd.c:322]
```
j_params = params_root->child;
    while(j_params != NULL) {
        if(j_params->type != cJSON_Number)
            continue;
        j_params = j_params->next;
        rp_params_cnt++;
}
```
if `j_params->type != cJSON_Number` fails results in an infinite loop.

**Comment by b-swat** [comment]
Thanks for pointing out the bug.
The fix will be included in the next release.
